- name: Install hunspell
  pacman:
    name:
      - hunspell
      - hunspell-de
      - hunspell-en_GB
      - hunspell-en_US
    state: present

- name: Install aspell
  pacman:
    name:
      - aspell
      - aspell-en
      - aspell-de
    state: present
